name: Daily Product Hunt Digest

on:
  schedule:
    - cron: '0 13 * * *'  # 8:00 AM EST (13:00 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-digest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Debug Environment
      run: |
        echo "Checking environment variables (masked):"
        echo "PRODUCT_HUNT_API_KEY exists: ${{ secrets.PRODUCT_HUNT_API_KEY != '' }}"
        echo "PRODUCT_HUNT_CLIENT_SECRET exists: ${{ secrets.PRODUCT_HUNT_CLIENT_SECRET != '' }}"
        echo "OPENAI_API_KEY exists: ${{ secrets.OPENAI_API_KEY != '' }}"
        echo "SLACK_BOT_TOKEN exists: ${{ secrets.SLACK_BOT_TOKEN != '' }}"
        echo "SLACK_CHANNEL_ID exists: ${{ secrets.SLACK_CHANNEL_ID != '' }}"
        echo "Current directory contents:"
        ls -la
        
    - name: Run digest script
      env:
        PRODUCT_HUNT_API_KEY: ${{ secrets.PRODUCT_HUNT_API_KEY }}
        PRODUCT_HUNT_CLIENT_SECRET: ${{ secrets.PRODUCT_HUNT_CLIENT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: |
        echo "Starting digest script..."
        node index.js
        echo "Script completed. Checking output files:"
        ls -la
        echo "Digest content:"
        cat competitive_digest.md 